name: Deletion of release versions
on:
  push:
  workflow_dispatch:

jobs:
  deletion-of-tags:
    runs-on: ubuntu-latest
    name: releases
    
    steps:
    - name: checkout
      uses: actions/checkout/@v3
         
   
    - name: delete
      run: |
         git tags -delete $(GENX_UAT_SP48_*/uk1.*)
         
