name: Delete Old Tags

on:
  workflow_dispatch:

jobs:
  delete_old_tags:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v2

      - name: List tags
        id: list_tags
        run: |
          git fetch --tags
          git for-each-ref --sort=taggerdate --format '%(refname:short) %(taggerdate:iso8601)' refs/tags | awk -v week_ago="$(date -d '1 week ago' --iso-8601=seconds)" '$2 < week_ago {print $1}' > old_tags.txt
        continue-on-error: true

      - name: Delete old tags
        if: steps.list_tags.outputs.stdout != ''
        run: |
          cat old_tags.txt | xargs -I {} git push --delete origin {}
