name: Deletion of release versions
on:
  push:
  workflow_dispatch:

jobs:
  deletion-of-tags:
    runs-on: ubuntu-latest
    name: releases
    
    steps:
    - name: checkout
      uses: actions/checkout/@v3

    - name: show list of tags
      run: |
        git tag -l "uk1.*" 
   
    - name: deletion
      run: |
       git tag | xargs git tag -d $("GENX_UAT_SP49_*/uk*")
