name: Send GitHub Actions Notifications to Microsoft Teams

on:
  workflow_run:
    workflows: UAT Tagging and Release
    types:
      - completed
      - workflow_run
  release:
    types:
      - created
  push:
    branches:
      - main

jobs:
  send_notification:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the code
        uses: actions/checkout@v2

      - name: Send Notification to Microsoft Teams on Workflow Trigger
        if: github.event_name == 'workflow_run'
        run: |
          MESSAGE="Workflow \`${{ github.event.workflow }}\` was triggered."
          PAYLOAD="{\"text\":\"$MESSAGE\"}"
          curl -X POST -H 'Content-Type: application/json' -d "$PAYLOAD" $TEAMS_WEBHOOK_URL_GEU
        env:
          TEAMS_WEBHOOK_URL_GEU: ${{ secrets.TEAMS_WEBHOOK_URL_GEU }}  

      - name: Send Notification to Microsoft Teams on Workflow Completion
        if: github.event_name == 'workflow_run' && github.event.workflow_run.conclusion != 'neutral'
        run: |
          MESSAGE="Workflow \`${{ github.event.workflow }}\` has completed with status: \`${{ github.event.workflow_run.conclusion }}\`."
          PAYLOAD="{\"text\":\"$MESSAGE\"}"
          curl -X POST -H 'Content-Type: application/json' -d "$PAYLOAD" $TEAMS_WEBHOOK_URL_GEU
        env:
          TEAMS_WEBHOOK_URL_GEU: ${{ secrets.TEAMS_WEBHOOK_URL_GEU }}  
      - name: Send Notification to Microsoft Teams on Release Creation
        if: github.event_name == 'release'
        run: |
          MESSAGE="A new release was created on branch \`${{ github.event.release.target_commitish }}\` with the tag \`${{ github.event.release.tag_name }}\`."
          MESSAGE+="\nRelease Notes: ${{ github.event.release.body }}"
          PAYLOAD="{\"text\":\"$MESSAGE\"}"
          curl -X POST -H 'Content-Type: application/json' -d "$PAYLOAD" $TEAMS_WEBHOOK_URL_GEU
        env:
          TEAMS_WEBHOOK_URL_GEU: ${{ secrets.TEAMS_WEBHOOK_URL_GEU }}  
