# .github/workflows/stale-branches.yml

name: Stale Branches

on:
  workflow_dispatch:
    
permissions:
  issues: write
  contents: write

jobs:
  stale_branches:
    runs-on: ubuntu-latest
    steps:
    - name: Stale Branches
      uses: crs-k/stale-branches@v3.0.0
